# Generated by RAD using generator based on datamodel-code-generator
#    source schema: cal_logs-1.0.0.yaml
#    time stamp:    VERSION CONTROLLED
# DO NOT EDIT THIS FILE DIRECTLY!

from __future__ import annotations

from typing import Annotated, ClassVar, List

from pydantic import Field, RootModel


class CalLogs(RootModel[List[str]]):
    schema_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/schemas/cal_logs-1.0.0"

    tag_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/tags/cal_logs-1.0.0"

    root: Annotated[List[str], Field(title='Calibration log messages')]
