# Generated by RAD using generator based on datamodel-code-generator
#    source schema: ephemeris-1.0.0.yaml
#    time stamp:    VERSION CONTROLLED
# DO NOT EDIT THIS FILE DIRECTLY!

from __future__ import annotations

from enum import Enum
from typing import Annotated, ClassVar

from pydantic import Field

from roman_datamodels.core._model import DataModel


class Type(Enum):
    DEFINITIVE = 'DEFINITIVE'
    PREDICTED = 'PREDICTED'


class Ephemeris(DataModel):
    """
    Ephemeris data information
    """

    schema_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/schemas/ephemeris-1.0.0"

    tag_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/tags/ephemeris-1.0.0"

    earth_angle: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.earth_angle', 'GuideWindow.earth_angle']},
            },
            title='[radians] Earth Angle',
        ),
    ]
    moon_angle: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.moon_angle', 'GuideWindow.moon_angle']},
            },
            title='[radians] Moon Angle',
        ),
    ]
    ephemeris_reference_frame: Annotated[
        str,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {
                    'datatype': 'nvarchar(10)',
                    'destination': ['ScienceCommon.ephemeris_reference_frame', 'GuideWindow.ephemeris_reference_frame'],
                },
            },
            title='Ephemeris reference frame',
        ),
    ]
    sun_angle: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.sun_angle', 'GuideWindow.sun_angle']},
            },
            title='[radians] Sun Angle',
        ),
    ]
    type: Annotated[
        Type,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {
                    'datatype': 'nvarchar(10)',
                    'destination': ['ScienceCommon.ephemeris_type', 'GuideWindow.ephemeris_type'],
                },
            },
            title='Type of ephemeris',
        ),
    ]
    time: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'Roman Science Data Processing (RSDP)'}},
                'archive_catalog': {
                    'datatype': 'float',
                    'destination': ['ScienceCommon.ephemeris_time', 'GuideWindow.ephemeris_time'],
                },
            },
            title='UTC time of position and velocity vectors in ephemeris (MJD)',
        ),
    ]
    spatial_x: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'Roman Science Data Processing (RSDP)'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.spatial_x', 'GuideWindow.spatial_x']},
            },
            title='[km] X spatial coordinate of Roman',
        ),
    ]
    spatial_y: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'Roman Science Data Processing (RSDP)'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.spatial_y', 'GuideWindow.spatial_y']},
            },
            title='[km] Y spatial coordinate of Roman',
        ),
    ]
    spatial_z: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'Roman Science Data Processing (RSDP)'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.spatial_z', 'GuideWindow.spatial_z']},
            },
            title='[km] Z spatial coordinate of Roman',
        ),
    ]
    velocity_x: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'Roman Science Data Processing (RSDP)'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.velocity_x', 'GuideWindow.velocity_x']},
            },
            title='[km/s] X component of Roman velocity',
        ),
    ]
    velocity_y: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'Roman Science Data Processing (RSDP)'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.velocity_y', 'GuideWindow.velocity_y']},
            },
            title='[km/s] Y component of Roman velocity',
        ),
    ]
    velocity_z: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'Roman Science Data Processing (RSDP)'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.velocity_z', 'GuideWindow.velocity_z']},
            },
            title='[km/s] Z component of Roman velocity',
        ),
    ]
