# Generated by RAD using generator based on datamodel-code-generator
#    source schema: exposure_type-1.0.0.yaml
#    time stamp:    VERSION CONTROLLED
# DO NOT EDIT THIS FILE DIRECTLY!

from __future__ import annotations

from enum import Enum
from typing import ClassVar


class ExposureType(Enum):
    WFI_IMAGE = 'WFI_IMAGE'
    WFI_GRISM = 'WFI_GRISM'
    WFI_PRISM = 'WFI_PRISM'
    WFI_DARK = 'WFI_DARK'
    WFI_FLAT = 'WFI_FLAT'
    WFI_WFSC = 'WFI_WFSC'
