# Generated by RAD using generator based on datamodel-code-generator
#    source schema: guidewindow_modes-1.0.0.yaml
#    time stamp:    VERSION CONTROLLED
# DO NOT EDIT THIS FILE DIRECTLY!

from __future__ import annotations

from enum import Enum
from typing import ClassVar


class GuidewindowModes(Enum):
    WIM_ACQ = 'WIM-ACQ'
    WIM_TRACK = 'WIM-TRACK'
    WSM_ACQ_1 = 'WSM-ACQ-1'
    WSM_ACQ_2 = 'WSM-ACQ-2'
    WSM_TRACK = 'WSM-TRACK'
    DEFOCUSED_MODERATE = 'DEFOCUSED-MODERATE'
    DEFOCUSED_LARGE = 'DEFOCUSED-LARGE'
