# Generated by RAD using generator based on datamodel-code-generator
#    source schema: guidestar-1.0.0.yaml
#    time stamp:    VERSION CONTROLLED
# DO NOT EDIT THIS FILE DIRECTLY!

from __future__ import annotations

from typing import Annotated, ClassVar

from pydantic import Field

from roman_datamodels.core._model import DataModel

from . import guidewindow_modes


class Guidestar(DataModel):
    """
    Guide star window information
    """

    schema_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/schemas/guidestar-1.0.0"

    tag_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/tags/guidestar-1.0.0"

    gw_id: Annotated[
        str,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'nvarchar(20)', 'destination': ['ScienceCommon.gw_id', 'GuideWindow.gw_id']},
            },
            title='guide star window identifier',
        ),
    ]
    gw_fgs_mode: Annotated[
        guidewindow_modes.GuidewindowModes,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {
                    'datatype': 'nvarchar(18)',
                    'destination': ['ScienceCommon.gw_fgs_mode', 'GuideWindow.gw_fgs_mode'],
                },
            }
        ),
    ]
    gs_id: Annotated[
        str,
        Field(
            description='guide star catalog id from the GSC2, field gsc2ID',
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'nvarchar(20)', 'destination': ['ScienceCommon.gs_id', 'GuideWindow.gs_id']},
            },
            title='guide star identifier from the GSC2 catalog',
        ),
    ]
    gs_catalog_version: Annotated[
        str,
        Field(
            description='The version of the catalog that the guide stars are selected, currently  "GSC 2.4.2", SDF should populate this from the return value of CAT e.g. CAT=GSC242',
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'nvarchar(20)', 'destination': ['ScienceCommon.gs_catalog_version']},
            },
            title='The version of the Guide Star Catalog',
        ),
    ]
    gs_ra: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.gs_ra', 'GuideWindow.gs_ra']},
            },
            title='[deg] guide star right ascension',
        ),
    ]
    gs_dec: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.gs_dec', 'GuideWindow.gs_dec']},
            },
            title='[deg] guide star declination',
        ),
    ]
    gs_ura: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.gs_ura', 'GuideWindow.gs_ura']},
            },
            title='[deg] guide star right ascension uncertainty',
        ),
    ]
    gs_udec: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.gs_udec', 'GuideWindow.gs_udec']},
            },
            title='[deg] guide star declination uncertainty',
        ),
    ]
    gs_mag: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.gs_mag', 'GuideWindow.gs_mag']},
            },
            title='guide star magnitude in detector',
        ),
    ]
    gs_umag: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.gs_umag', 'GuideWindow.gs_umag']},
            },
            title='guide star magnitude uncertainty',
        ),
    ]
    data_start: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.data_start', 'GuideWindow.data_start']},
            },
            title='MJD start time of guider data within this file',
        ),
    ]
    data_end: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.data_end', 'GuideWindow.data_end']},
            },
            title='MJD end time of guider data within this file',
        ),
    ]
    gs_ctd_x: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.gs_ctd_x', 'GuideWindow.gs_ctd_x']},
            },
            title='[arcsec] guide star centroid x position in guider ideal frame',
        ),
    ]
    gs_ctd_y: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.gs_ctd_y', 'GuideWindow.gs_ctd_y']},
            },
            title='[arcsec] guide star centroid y position in guider ideal frame',
        ),
    ]
    gs_ctd_ux: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.gs_ctd_ux', 'GuideWindow.gs_ctd_ux']},
            },
            title='uncertainty in the x position of the centroid',
        ),
    ]
    gs_ctd_uy: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.gs_ctd_uy', 'GuideWindow.gs_ctd_uy']},
            },
            title='uncertainty in the y position of the centroid',
        ),
    ]
    gs_epoch: Annotated[
        str,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {
                    'datatype': 'nvarchar(10)',
                    'destination': ['ScienceCommon.gs_epoch', 'GuideWindow.gs_epoch'],
                },
            },
            title='Epoch of guide star coordinates',
        ),
    ]
    gs_mura: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.gs_mura', 'GuideWindow.gs_mura']},
            },
            title='[mas/yr] Guide star ICRS right ascension proper motion',
        ),
    ]
    gs_mudec: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.gs_mudec', 'GuideWindow.gs_mudec']},
            },
            title='[mas/yr] Guide star ICRS declination proper motion',
        ),
    ]
    gs_para: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.gs_para', 'GuideWindow.gs_para']},
            },
            title='Guide star annual parallax',
        ),
    ]
    gs_pattern_error: Annotated[
        float,
        Field(
            description='RMS of guide star position in guide window from pattern matching (error on centroid not explicitly calculated, the FACE information takes all the centroids and calculates the error across the guiding pattern)',
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {
                    'datatype': 'float',
                    'destination': ['ScienceCommon.gs_pattern_error', 'GuideWindow.gs_pattern_error'],
                },
            },
            title='RMS of guide star position',
        ),
    ]
    gw_window_xstart: Annotated[
        int,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'Science Data Formatting'}},
                'archive_catalog': {'datatype': 'int', 'destination': ['ScienceCommon.gw_window_xstart']},
            },
            title='Guide window x start position on the detector',
        ),
    ]
    gw_window_ystart: Annotated[
        int,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'Science Data Formatting'}},
                'archive_catalog': {'datatype': 'int', 'destination': ['ScienceCommon.gw_window_ystart']},
            },
            title='Guide window y start position on the detector',
        ),
    ]
    gw_window_xstop: Annotated[
        int,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'Science Data Formatting'}},
                'archive_catalog': {'datatype': 'int', 'destination': ['ScienceCommon.gw_window_xstop']},
            },
            title='Guide window x stop position on the detector',
        ),
    ]
    gw_window_ystop: Annotated[
        int,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'Science Data Formatting'}},
                'archive_catalog': {'datatype': 'int', 'destination': ['ScienceCommon.gw_window_ystop']},
            },
            title='Guide window y stop position on the detector',
        ),
    ]
    gw_window_xsize: Annotated[
        int,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'Science Data Formatting'}},
                'archive_catalog': {'datatype': 'int', 'destination': ['ScienceCommon.gw_window_xsize']},
            },
            title='Guide window size in the x direction in detector coordinates',
        ),
    ]
    gw_window_ysize: Annotated[
        int,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'Science Data Formatting'}},
                'archive_catalog': {'datatype': 'int', 'destination': ['ScienceCommon.gw_window_ysize']},
            },
            title='Guide window size in the y direction in detector coordinates',
        ),
    ]
