# Generated by RAD using generator based on datamodel-code-generator
#    source schema: observation-1.0.0.yaml
#    time stamp:    VERSION CONTROLLED
# DO NOT EDIT THIS FILE DIRECTLY!

from __future__ import annotations

from enum import Enum
from typing import Annotated, ClassVar

from pydantic import Field

from roman_datamodels.core._model import DataModel


class Survey(Enum):
    HLS = 'HLS'
    EMS = 'EMS'
    SN = 'SN'
    N_A = 'N/A'


class Observation(DataModel):
    """
    Observation identifiers
    """

    schema_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/schemas/observation-1.0.0"

    tag_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/tags/observation-1.0.0"

    obs_id: Annotated[
        str,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'nvarchar(28)', 'destination': ['ScienceCommon.obs_id', 'GuideWindow.obs_id']},
            },
            title="Programmatic observation identifier. The format is 'PPPPPCCAAASSSOOOVVVggsaaeeee' where 'PPPPP' is the Program, 'CC' is the execution plan, 'AAA' is the pass, 'SSS' is the segment, 'OOO' is the Observation, 'VVV' is the Visit, 'gg' is the visit file group, 's' is the visit file sequence, 'aa' is the visit file activity, and 'eeee' is the exposure ID. The observation ID is the complete concatenation of visit_id + visit_file_statement (visit_file_group + visit_file_sequence + visit_file_activity) + exposure.",
        ),
    ]
    visit_id: Annotated[
        str,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {
                    'datatype': 'nvarchar(19)',
                    'destination': ['ScienceCommon.visit_id', 'GuideWindow.visit_id'],
                },
            },
            title="A unique identifier for a visit. The format is 'PPPPPCCAAASSSOOOVVV' where 'PPPPP' is the Program, 'CC' is the execution plan, 'AAA' is the pass, 'SSS' is the segment number, 'OOO' is the Observation and 'VVV' is the Visit.",
        ),
    ]
    program: Annotated[
        str,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'int', 'destination': ['ScienceCommon.program', 'GuideWindow.program']},
            },
            title="Program number, defined range is 1..18445; included in obs_id and visit_id as 'PPPPP'.",
        ),
    ]
    execution_plan: Annotated[
        int,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {
                    'datatype': 'smallint',
                    'destination': ['ScienceCommon.execution_plan', 'GuideWindow.execution_plan'],
                },
            },
            title="Execution plan within the program, defined range is 1..99; included in obs_id and visit_id as 'CC'.",
        ),
    ]
    pass_: Annotated[
        int,
        Field(
            alias='pass',
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'smallint', 'destination': ['ScienceCommon.pass', 'GuideWindow.pass']},
            },
            title="Pass number within execution plan, defined range is 1..999; included in obs_id and visit_id as 'AA'.",
        ),
    ]
    segment: Annotated[
        int,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'smallint', 'destination': ['ScienceCommon.segment', 'GuideWindow.segment']},
            },
            title="Segment Number within pass, defined range is 1..999; included in obs_id and visit_id as 'SSS'.",
        ),
    ]
    observation: Annotated[
        int,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {
                    'datatype': 'smallint',
                    'destination': ['ScienceCommon.observation', 'GuideWindow.observation'],
                },
            },
            title="Observation number within the segment, defined range is 1..999; included in obs_id and visit_id as 'OOO'.",
        ),
    ]
    visit: Annotated[
        int,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'smallint', 'destination': ['ScienceCommon.visit', 'GuideWindow.visit']},
            },
            title="Visit number within the observation, defined range of values is 1..999; included in obs_id and visit_id as 'VVV'.",
        ),
    ]
    visit_file_group: Annotated[
        int,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {
                    'datatype': 'smallint',
                    'destination': ['ScienceCommon.visit_file_group', 'GuideWindow.visit_file_group'],
                },
            },
            title="Sequence group within the visit file, defined range of values is 1..99; included in obs_id as 'gg'.",
        ),
    ]
    visit_file_sequence: Annotated[
        int,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {
                    'datatype': 'tinyint',
                    'destination': ['ScienceCommon.visit_file_sequence', 'GuideWindow.visit_file_sequence'],
                },
            },
            title="Visit file sequence within the group, defined range of values is 1..5; included in obs_id as 's'.",
        ),
    ]
    visit_file_activity: Annotated[
        str,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {
                    'datatype': 'nvarchar(2)',
                    'destination': ['ScienceCommon.visit_file_activity', 'GuideWindow.visit_file_activity'],
                },
            },
            title="Visit file activity within the sequence, defined range of values is 1..ZZ; included in obs_id as 'aa'.",
        ),
    ]
    exposure: Annotated[
        int,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {
                    'datatype': 'int',
                    'destination': ['ScienceCommon.observation_exposure', 'GuideWindow.observation_exposure'],
                },
            },
            title="Exposure within the visit, defined range of values is 1..9999; included in obs_id as 'eeee'.",
        ),
    ]
    template: Annotated[
        str,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'PSS:dms_visit.template'}},
                'archive_catalog': {
                    'datatype': 'nvarchar(50)',
                    'destination': ['ScienceCommon.template', 'GuideWindow.template'],
                },
            },
            title='Observation template used',
        ),
    ]
    observation_label: Annotated[
        str,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {
                    'datatype': 'nvarchar(max)',
                    'destination': ['ScienceCommon.observation_label', 'GuideWindow.observation_label'],
                },
            },
            title='Proposer label for the observation',
        ),
    ]
    survey: Annotated[
        Survey,
        Field(
            json_schema_extra={
                'archive_catalog': {'datatype': 'nvarchar(15)', 'destination': ['ScienceCommon.survey', 'GuideWindow.survey']}
            },
            title='Observation Survey',
        ),
    ]
