# Generated by RAD using generator based on datamodel-code-generator
#    source schema: pointing-1.0.0.yaml
#    time stamp:    VERSION CONTROLLED
# DO NOT EDIT THIS FILE DIRECTLY!

from __future__ import annotations

from typing import Annotated, ClassVar

from pydantic import Field

from roman_datamodels.core._model import DataModel


class Pointing(DataModel):
    """
    Spacecraft pointing information
    """

    schema_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/schemas/pointing-1.0.0"

    tag_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/tags/pointing-1.0.0"

    ra_v1: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.ra_v1', 'GuideWindow.ra_v1']},
            },
            title='[deg] RA of telescope V1 axis',
        ),
    ]
    dec_v1: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.dec_v1', 'GuideWindow.dec_v1']},
            },
            title='[deg] Dec of telescope V1 axis',
        ),
    ]
    pa_v3: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.pa_v3', 'GuideWindow.pa_v3']},
            },
            title='[deg] Position angle of telescope V3 axis',
        ),
    ]
