# Generated by RAD using generator based on datamodel-code-generator
#    source schema: ref_optical_element-1.0.0.yaml
#    time stamp:    VERSION CONTROLLED
# DO NOT EDIT THIS FILE DIRECTLY!

from __future__ import annotations

from typing import ClassVar

from roman_datamodels.core._base import BaseDataModel

from . import wfi_optical_element


class instrument(BaseDataModel):
    schema_uri: ClassVar[None] = None
    optical_element: wfi_optical_element.WfiOpticalElement


class RefOpticalElement(BaseDataModel):
    """
    Name of the filter element used
    """

    schema_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/schemas/ref_optical_element-1.0.0"

    instrument: instrument
