# Generated by RAD using generator based on datamodel-code-generator
#    source schema: velocity_aberration-1.0.0.yaml
#    time stamp:    VERSION CONTROLLED
# DO NOT EDIT THIS FILE DIRECTLY!

from __future__ import annotations

from typing import Annotated, ClassVar

from pydantic import Field

from roman_datamodels.core._model import DataModel


class VelocityAberration(DataModel):
    """
    Velocity aberration correction information
    """

    schema_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/schemas/velocity_aberration-1.0.0"

    tag_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/tags/velocity_aberration-1.0.0"

    ra_offset: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.ra_offset', 'GuideWindow.ra_offset']},
            },
            title='Velocity aberration right ascension offset',
        ),
    ]
    dec_offset: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.dec_offset', 'GuideWindow.dec_offset']},
            },
            title='Velocity aberration declination offset',
        ),
    ]
    scale_factor: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {
                    'datatype': 'float',
                    'destination': ['ScienceCommon.scale_factor', 'GuideWindow.scale_factor'],
                },
            },
            title='Velocity aberration scale factor',
        ),
    ]
