# Generated by RAD using generator based on datamodel-code-generator
#    source schema: wcsinfo-1.0.0.yaml
#    time stamp:    VERSION CONTROLLED
# DO NOT EDIT THIS FILE DIRECTLY!

from __future__ import annotations

from typing import Annotated, ClassVar

from pydantic import Field

from roman_datamodels.core._model import DataModel


class Wcsinfo(DataModel):
    """
    WCS parameters
    """

    schema_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/schemas/wcsinfo-1.0.0"

    tag_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/tags/wcsinfo-1.0.0"

    v2_ref: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.v2_ref', 'GuideWindow.v2_ref']},
            },
            title='[arcsec] Telescope v2 coordinate of the reference point',
        ),
    ]
    v3_ref: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.v3_ref', 'GuideWindow.v3_ref']},
            },
            title='[arcsec] Telescope v3 coordinate of the reference point',
        ),
    ]
    vparity: Annotated[
        int,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'int', 'destination': ['ScienceCommon.vparity', 'GuideWindow.vparity']},
            },
            title='Relative sense of rotation between Ideal xy and V2V3',
        ),
    ]
    v3yangle: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.v3yangle', 'GuideWindow.v3yangle']},
            },
            title='[deg] Angle from V3 axis to Ideal y axis',
        ),
    ]
    ra_ref: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.ra_ref', 'GuideWindow.ra_ref']},
            },
            title='[deg] Right ascension of the reference point',
        ),
    ]
    dec_ref: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.dec_ref', 'GuideWindow.dec_ref']},
            },
            title='[deg] Declination of the reference point',
        ),
    ]
    roll_ref: Annotated[
        float,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {'datatype': 'float', 'destination': ['ScienceCommon.roll_ref', 'GuideWindow.roll_ref']},
            },
            title='[deg] V3 roll angle at the ref point (N over E)',
        ),
    ]
    s_region: Annotated[
        str,
        Field(
            json_schema_extra={
                'sdf': {'special_processing': 'VALUE_REQUIRED', 'source': {'origin': 'TBD'}},
                'archive_catalog': {
                    'datatype': 'nvarchar(max)',
                    'destination': ['ScienceCommon.s_region', 'GuideWindow.s_region'],
                },
            },
            title='spatial extent of the observation',
        ),
    ]
