# Generated by RAD using generator based on datamodel-code-generator
#    source schema: wfi_optical_element-1.0.0.yaml
#    time stamp:    VERSION CONTROLLED
# DO NOT EDIT THIS FILE DIRECTLY!

from __future__ import annotations

from enum import Enum
from typing import ClassVar


class WfiOpticalElement(Enum):
    F062 = 'F062'
    F087 = 'F087'
    F106 = 'F106'
    F129 = 'F129'
    F146 = 'F146'
    F158 = 'F158'
    F184 = 'F184'
    F213 = 'F213'
    GRISM = 'GRISM'
    PRISM = 'PRISM'
    DARK = 'DARK'
