# Generated by RAD using generator based on datamodel-code-generator
#    source schema: wfi_detector-1.0.0.yaml
#    time stamp:    VERSION CONTROLLED
# DO NOT EDIT THIS FILE DIRECTLY!

from __future__ import annotations

from enum import Enum
from typing import ClassVar


class WfiDetector(Enum):
    WFI01 = 'WFI01'
    WFI02 = 'WFI02'
    WFI03 = 'WFI03'
    WFI04 = 'WFI04'
    WFI05 = 'WFI05'
    WFI06 = 'WFI06'
    WFI07 = 'WFI07'
    WFI08 = 'WFI08'
    WFI09 = 'WFI09'
    WFI10 = 'WFI10'
    WFI11 = 'WFI11'
    WFI12 = 'WFI12'
    WFI13 = 'WFI13'
    WFI14 = 'WFI14'
    WFI15 = 'WFI15'
    WFI16 = 'WFI16'
    WFI17 = 'WFI17'
    WFI18 = 'WFI18'
