# Generated by RAD using generator based on datamodel-code-generator
#    source schema: data_products/msos_stack-1.0.0.yaml
#    time stamp:    VERSION CONTROLLED
# DO NOT EDIT THIS FILE DIRECTLY!

from __future__ import annotations

from typing import Annotated, ClassVar

from pydantic import Field

from roman_datamodels.core._model import DataModel
from roman_datamodels.core.adaptors import NdArray, np

from .. import common


class MsosStackModel(DataModel):
    """
    MSOS Stack Level 3 Schema

    """

    schema_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/schemas/data_products/msos_stack-1.0.0"

    tag_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/tags/data_products/msos_stack-1.0.0"

    meta: common.Common
    data: Annotated[NdArray[np.float64, 2, (4096, 4096)], Field(title='Flux data')]
    uncertainty: Annotated[NdArray[np.float64, 2, (4096, 4096)], Field(title='uncertainty data')]
    mask: Annotated[NdArray[np.uint8, 2, (4096, 4096)], Field(title='mask data')]
    coverage: Annotated[NdArray[np.uint8, 2, (4096, 4096)], Field(title='coverage data')]
