# Generated by RAD using generator based on datamodel-code-generator
#    source schema: data_products/ramp_fit_output-1.0.0.yaml
#    time stamp:    VERSION CONTROLLED
# DO NOT EDIT THIS FILE DIRECTLY!

from __future__ import annotations

from typing import Annotated, ClassVar

from pydantic import Field

from roman_datamodels.core._model import DataModel
from roman_datamodels.core.adaptors import AstropyQuantity, NdArray, Unit, np

from .. import common


class RampFitOutputModel(DataModel):
    """
    Ramp fit output schema
    """

    schema_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/schemas/data_products/ramp_fit_output-1.0.0"

    tag_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/tags/data_products/ramp_fit_output-1.0.0"

    meta: common.Common
    slope: Annotated[AstropyQuantity[np.float32, 3, Unit("electron / s"), (8, 4096, 4096)], Field(title='Segment-specific slope')]
    sigslope: Annotated[
        AstropyQuantity[np.float32, 3, Unit("electron / s"), (8, 4096, 4096)], Field(title='Sigma for segment-specific slope')
    ]
    yint: Annotated[
        AstropyQuantity[np.float32, 3, Unit("electron"), (8, 4096, 4096)], Field(title='Segment-specific y-intercept')
    ]
    sigyint: Annotated[
        AstropyQuantity[np.float32, 3, Unit("electron"), (8, 4096, 4096)], Field(title='Sigma for segment-specific y-intercept')
    ]
    pedestal: Annotated[AstropyQuantity[np.float32, 2, Unit("electron"), (4096, 4096)], Field(title='Pedestal array')]
    weights: Annotated[NdArray[np.float32, 3, (8, 4096, 4096)], Field(title='Weights for segment-specific fits')]
    crmag: Annotated[AstropyQuantity[np.float32, 3, Unit("electron"), (8, 4096, 4096)], Field(title='Approximate CR magnitudes')]
    var_poisson: Annotated[
        AstropyQuantity[np.float32, 3, Unit("electron2 / s2"), (8, 4096, 4096)],
        Field(title='Variance due to poisson noise for segment-specific slope'),
    ]
    var_rnoise: Annotated[
        AstropyQuantity[np.float32, 3, Unit("electron2 / s2"), (8, 4096, 4096)],
        Field(title='Variance due to read noise for segment-specific slope'),
    ]
