# Generated by RAD using generator based on datamodel-code-generator
#    source schema: reference_files/distortion-1.0.0.yaml
#    time stamp:    VERSION CONTROLLED
# DO NOT EDIT THIS FILE DIRECTLY!

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, ClassVar

from pydantic import Field

from roman_datamodels.core._model import DataModel
from roman_datamodels.core.adaptors import AstropyUnit, Unit

from ..ref_common import RefCommon
from ..ref_optical_element import RefOpticalElement


class reftype(Enum):
    DISTORTION = 'DISTORTION'


class meta(RefCommon, RefOpticalElement):
    schema_uri: ClassVar[None] = None
    reftype: reftype
    input_units: Annotated[AstropyUnit[Unit("pixel")], Field(title='Units of the detector coordinate inputs to this model.')]
    output_units: Annotated[
        AstropyUnit[Unit("arcsec")], Field(title='Output units of V2/V3 coordinates after the model is applied.')
    ]


class DistortionRefModel(DataModel):
    """
    Distortion reference schema
    """

    schema_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/schemas/reference_files/distortion-1.0.0"

    tag_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/tags/reference_files/distortion-1.0.0"

    meta: meta
    coordinate_distortion_transform: Annotated[Any, Field(title='Distortion transform as an instance of astropy.modeling.Model.')]
