# Generated by RAD using generator based on datamodel-code-generator
#    source schema: reference_files/mask-1.0.0.yaml
#    time stamp:    VERSION CONTROLLED
# DO NOT EDIT THIS FILE DIRECTLY!

from __future__ import annotations

from enum import Enum
from typing import Annotated, ClassVar

from pydantic import Field

from roman_datamodels.core._extended import _MaskRefModel
from roman_datamodels.core.adaptors import NdArray, np

from ..ref_common import RefCommon


class reftype(Enum):
    MASK = 'MASK'


class meta(RefCommon):
    schema_uri: ClassVar[None] = None
    reftype: reftype


class MaskRefModel(_MaskRefModel):
    """
    DQ Mask reference schema
    """

    schema_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/schemas/reference_files/mask-1.0.0"

    tag_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/tags/reference_files/mask-1.0.0"

    meta: meta
    dq: Annotated[NdArray[np.uint32, 2, (4096, 4096)], Field(title='Data quality mask array')]
