# Generated by RAD using generator based on datamodel-code-generator
#    source schema: reference_files/pixelarea-1.0.0.yaml
#    time stamp:    VERSION CONTROLLED
# DO NOT EDIT THIS FILE DIRECTLY!

from __future__ import annotations

from enum import Enum
from typing import Annotated, ClassVar, Optional

from pydantic import Field

from roman_datamodels.core._base import BaseDataModel
from roman_datamodels.core._model import DataModel
from roman_datamodels.core.adaptors import AstropyQuantity, NdArray, Unit, np

from ..ref_common import RefCommon
from ..ref_optical_element import RefOpticalElement


class reftype(Enum):
    AREA = 'AREA'


class Photometry(BaseDataModel):
    schema_uri: ClassVar[None] = None
    pixelarea_steradians: Annotated[
        Optional[AstropyQuantity[np.float64, 0, Unit("sr")]], Field(title='Nominal pixel area in steradians')
    ]
    pixelarea_arcsecsq: Annotated[
        Optional[AstropyQuantity[np.float64, 0, Unit("arcsec**2")]], Field(title='Nominal pixel area in arcsec^2')
    ]


class meta(RefCommon, RefOpticalElement):
    schema_uri: ClassVar[None] = None
    reftype: reftype
    photometry: Photometry


class PixelareaRefModel(DataModel):
    """
    Pixel area reference schema
    """

    schema_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/schemas/reference_files/pixelarea-1.0.0"

    tag_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/tags/reference_files/pixelarea-1.0.0"

    meta: meta
    data: Annotated[NdArray[np.float32, 2, (4096, 4096)], Field(title='Pixel area array')]
