# Generated by RAD using generator based on datamodel-code-generator
#    source schema: reference_files/readnoise-1.0.0.yaml
#    time stamp:    VERSION CONTROLLED
# DO NOT EDIT THIS FILE DIRECTLY!

from __future__ import annotations

from enum import Enum
from typing import Annotated, ClassVar

from pydantic import Field

from roman_datamodels.core._model import DataModel
from roman_datamodels.core.adaptors import AstropyQuantity, Unit, np

from ..ref_common import RefCommon
from ..ref_exposure_type import RefExposureType


class reftype(Enum):
    READNOISE = 'READNOISE'


class meta(RefCommon, RefExposureType):
    schema_uri: ClassVar[None] = None
    reftype: reftype


class ReadnoiseRefModel(DataModel):
    """
    Read noise reference schema
    """

    schema_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/schemas/reference_files/readnoise-1.0.0"

    tag_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/tags/reference_files/readnoise-1.0.0"

    meta: meta
    data: Annotated[AstropyQuantity[np.float32, 2, Unit("DN"), (4096, 4096)], Field(title='Read noise data array')]
