# Generated by RAD using generator based on datamodel-code-generator
#    source schema: reference_files/refpix-1.0.0.yaml
#    time stamp:    VERSION CONTROLLED
# DO NOT EDIT THIS FILE DIRECTLY!

from __future__ import annotations

from enum import Enum
from typing import Annotated, ClassVar

from pydantic import Field

from roman_datamodels.core._model import DataModel
from roman_datamodels.core.adaptors import AstropyUnit, NdArray, Unit, np

from ..ref_common import RefCommon


class reftype(Enum):
    REFPIX = 'REFPIX'


class meta(RefCommon):
    schema_uri: ClassVar[None] = None
    reftype: reftype
    input_units: Annotated[AstropyUnit[Unit("DN")], Field(title='Units of the input to the linearity polynomial.')]
    output_units: Annotated[AstropyUnit[Unit("DN")], Field(title='Units of the output of the linearity polynomial.')]


class RefpixRefModel(DataModel):
    """
    Reference Pixel Correction Reference Schema
    """

    schema_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/schemas/reference_files/refpix-1.0.0"

    tag_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/tags/reference_files/refpix-1.0.0"

    meta: meta
    gamma: Annotated[NdArray[np.complex128, 2, (32, 286721)], Field(title='Left column correction coefficients')]
    zeta: Annotated[NdArray[np.complex128, 2, (32, 286721)], Field(title='Right column correction coefficients')]
    alpha: Annotated[NdArray[np.complex128, 2, (32, 286721)], Field(title='Reference output correction coefficients')]
