# Generated by RAD using generator based on datamodel-code-generator
#    source schema: reference_files/wfi_img_photom-1.0.0.yaml
#    time stamp:    VERSION CONTROLLED
# DO NOT EDIT THIS FILE DIRECTLY!

from __future__ import annotations

from enum import Enum
from typing import Annotated, ClassVar, Dict, Optional

from pydantic import Field

from roman_datamodels.core._base import BaseDataModel
from roman_datamodels.core._model import DataModel
from roman_datamodels.core.adaptors import AstropyQuantity, Unit, np

from ..ref_common import RefCommon


class reftype(Enum):
    PHOTOM = 'PHOTOM'


class PhotTable(BaseDataModel):
    schema_uri: ClassVar[None] = None
    photmjsr: Annotated[
        Optional[AstropyQuantity[np.float64, 0, Unit("MJy.sr**-1")]], Field(title='Surface brightness, in MJy/steradian')
    ]
    uncertainty: Annotated[
        Optional[AstropyQuantity[np.float64, 0, Unit("MJy.sr**-1")]],
        Field(title='Uncertainty of surface brightness, in MJy/steradian'),
    ]
    pixelareasr: Annotated[Optional[AstropyQuantity[np.float64, 0, Unit("sr")]], Field(title='Nominal pixel area, in steradian')]


class meta(RefCommon):
    schema_uri: ClassVar[None] = None
    reftype: reftype


class WfiImgPhotomRefModel(DataModel):
    """
    WFI imaging photometric flux conversion data model
    """

    schema_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/schemas/reference_files/wfi_img_photom-1.0.0"

    tag_uri: ClassVar[str] = "asdf://stsci.edu/datamodels/roman/tags/reference_files/wfi_img_photom-1.0.0"

    meta: meta
    phot_table: Annotated[Dict[str, PhotTable], Field(title='Photometric flux conversion factors table')]
